### ISSUE TITLE
Unable to deploy app - expired tls certificate

### ISSUE THREAD

**Issue by brmadsen** [f5devcentral/xcwaapdemoguide#1]
Hi All,

When I try and run kubectl tool from the command line to deploy the sample app, I get a message

C:\Users\ben>kubectl.exe --kubeconfig ves_b-madsen_b-madsen-vk8.yaml apply -f vk8s-manifest.yaml
Unable to connect to the server: remote error: tls: expired certificate

Any ideas?

Thanks

**Comment by yoctoalex** [comment]
Hello,

Try to generate a new certificate as described here: https://github.com/f5devcentral/xcwaapdemoguide#create-virtual-kubernetes-vk8s-cluster 

![Screenshot 2022-10-17 210615](https://user-images.githubusercontent.com/20835203/196261715-a8536252-8a42-4268-836b-951899ad5925.jpg)

Thanks,
Alex
