### ISSUE TITLE
Clarity around service names

### ISSUE THREAD

**Issue by garynewe** [f5devcentral/xcwaapdemoguide#2]
Please note that it follows the format of servicename.namespace. We use star-ratings-app.github for this demo.
This is perhaps a little unclear, while you have outlined the correct syntax an inexperienced user may try to apply "star-ratings-app.github" when setting up the origin server.

Suggest you include an example so say star-ratings-app."yournamespace" as an example?

**Comment by yoctoalex** [comment]
Hello,

Thank you for the improvement. The fix to the Readme has been applied.
